name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy packages on digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          envs: GITHUB_TOKEN
          script: |
            cd open-discourse-droplet
            git pull
            docker-compose down
            docker system prune -af
            docker image prune -f
            docker volume rm $(docker volume ls -q --filter dangling=true)
            docker volume prune -f
            docker login docker.pkg.github.com -u open-discourse -p $GITHUB_TOKEN
            docker-compose --env-file .env up -d
